# Generated by Django 5.1.3 on 2024-12-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_description', models.CharField(max_length=1000)),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('product_category', models.CharField(max_length=50)),
            ],
        ),
    ]
